sudo: required
dist: trusty
language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y potrace
script:
  # Unfortunately, `npm audit` is failing, and it doesn't look like there's any easy fix.
  # See https://github.com/cubing/icons/issues/55
  # - npm audit
  - ./load-ssh-key npm run deploy
